name: Build AntiTheft APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Unzip project (if ZIP file exists)
        run: |
          if [ -f project.zip ]; then
            unzip -o project.zip -d project
          fi

      - name: Replace phone number in SecurityEventHandler.kt
        run: |
          find ./ -type f -name "SecurityEventHandler.kt" -exec sed -i 's/\+201000000000/+
